/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults, RouterHistory, } from "@stencil/router";
export namespace Components {
    interface AppRoot {
    }
    interface CreateRental {
        "history": RouterHistory;
    }
    interface CustomerHandover {
        "history": RouterHistory;
    }
    interface HandoverList {
        "history": RouterHistory;
    }
    interface RentalAgreement {
        "history": RouterHistory;
        "match": MatchResults;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCreateRentalElement extends Components.CreateRental, HTMLStencilElement {
    }
    var HTMLCreateRentalElement: {
        prototype: HTMLCreateRentalElement;
        new (): HTMLCreateRentalElement;
    };
    interface HTMLCustomerHandoverElement extends Components.CustomerHandover, HTMLStencilElement {
    }
    var HTMLCustomerHandoverElement: {
        prototype: HTMLCustomerHandoverElement;
        new (): HTMLCustomerHandoverElement;
    };
    interface HTMLHandoverListElement extends Components.HandoverList, HTMLStencilElement {
    }
    var HTMLHandoverListElement: {
        prototype: HTMLHandoverListElement;
        new (): HTMLHandoverListElement;
    };
    interface HTMLRentalAgreementElement extends Components.RentalAgreement, HTMLStencilElement {
    }
    var HTMLRentalAgreementElement: {
        prototype: HTMLRentalAgreementElement;
        new (): HTMLRentalAgreementElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "create-rental": HTMLCreateRentalElement;
        "customer-handover": HTMLCustomerHandoverElement;
        "handover-list": HTMLHandoverListElement;
        "rental-agreement": HTMLRentalAgreementElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface CreateRental {
        "history"?: RouterHistory;
    }
    interface CustomerHandover {
        "history"?: RouterHistory;
    }
    interface HandoverList {
        "history"?: RouterHistory;
    }
    interface RentalAgreement {
        "history"?: RouterHistory;
        "match"?: MatchResults;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "create-rental": CreateRental;
        "customer-handover": CustomerHandover;
        "handover-list": HandoverList;
        "rental-agreement": RentalAgreement;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "create-rental": LocalJSX.CreateRental & JSXBase.HTMLAttributes<HTMLCreateRentalElement>;
            "customer-handover": LocalJSX.CustomerHandover & JSXBase.HTMLAttributes<HTMLCustomerHandoverElement>;
            "handover-list": LocalJSX.HandoverList & JSXBase.HTMLAttributes<HTMLHandoverListElement>;
            "rental-agreement": LocalJSX.RentalAgreement & JSXBase.HTMLAttributes<HTMLRentalAgreementElement>;
        }
    }
}
